from collections import OrderedDict

categories = {
"antiques": "craigslist.org/search/ata",
"appliances": "craigslist.org/search/ppa",
"arts+crafts": "craigslist.org/search/ara",
"atv/utv/sno": "craigslist.org/search/sna",
"auto parts": "craigslist.org/search/pta",
"wheels/tires": "craigslist.org/search/wta",
"baby+kid": "craigslist.org/search/baa",
"barter": "craigslist.org/search/bar",
"beauty+hlth": "craigslist.org/search/haa",
"bikes": "craigslist.org/search/bia",
"bike parts": "craigslist.org/search/bip",
"boats": "craigslist.org/search/boo",
"boat parts": "craigslist.org/search/bpa",
"books": "craigslist.org/search/bka",
"business": "craigslist.org/search/bfa",
"cars+trucks": "craigslist.org/search/cta",
"cds/dvd/vhs": "craigslist.org/search/ema",
"cell phones": "craigslist.org/search/moa",
"clothes+acc": "craigslist.org/search/cla",
"collectibles": "craigslist.org/search/cba",
"computers": "craigslist.org/search/sya",
"computer parts": "craigslist.org/search/syp",
"electronics": "craigslist.org/search/ela",
"farm+garden": "craigslist.org/search/gra",
"free": "craigslist.org/search/zip",
"furniture": "craigslist.org/search/fua",
"garage sale": "craigslist.org/search/gms",
"general": "craigslist.org/search/foa",
"heavy equip": "craigslist.org/search/hva",
"household": "craigslist.org/search/hsa",
"jewelry": "craigslist.org/search/jwa",
"materials": "craigslist.org/search/maa",
"motorcycles": "craigslist.org/search/mca",
"motorcycle parts": "craigslist.org/search/mpa",
"music instr": "craigslist.org/search/msa",
"photo+video": "craigslist.org/search/pha",
"rvs+camp": "craigslist.org/search/rva",
"sporting": "craigslist.org/search/sga",
"tickets": "craigslist.org/search/tia",
"tools": "craigslist.org/search/tla",
"toys+games": "craigslist.org/search/taa",
"trailers": "craigslist.org/search/tra",
"video gaming": "craigslist.org/search/vga",
"wanted": "craigslist.org/search/waa"}

searchIndex = OrderedDict(sorted(categories.items(), key=lambda t: t[0]))
