from collections import OrderedDict

locations = {
'akron / canton': 'akroncanton',
'albany, GA': 'albanyga',
'albany, NY': 'albany',
'albuquerque': 'albuquerque',
'altoona-johnstown': 'altoona',
'amarillo, TX': 'amarillo',
'ames, IA': 'ames',
'anchorage / mat-su': 'anchorage',
'annapolis, MD': 'annapolis',
'ann arbor, MI': 'annarbor',
'appleton-oshkosh-FDL': 'appleton',
'asheville, NC': 'asheville',
'ashtabula, OH': 'ashtabula',
'athens, GA': 'athensga',
'athens, OH': 'athensohio',
'atlanta, GA': 'atlanta',
'auburn, AL': 'auburn',
'augusta, GA': 'augusta',
'austin, TX': 'austin',
'bakersfield, CA': 'bakersfield',
'baltimore, MD': 'baltimore',
'baton rouge': 'batonrouge',
'battle creek, MI': 'battlecreek',
'beaumont / port arthur': 'beaumont',
'bellingham, WA': 'bellingham',
'bemidji, MN': 'bemidji',
'bend, OR': 'bend',
'billings, MT': 'billings',
'binghamton, NY': 'binghamton',
'birmingham, AL': 'bham',
'bismarck, ND': 'bismarck',
'bloomington, IN': 'bloomington',
'bloomington-normal': 'bn',
'boise, ID': 'boise',
'boone, NC': 'boone',
'bostonnorth shore, south shore': 'boston',
'boulder, CO': 'boulder',
'bowling green, KY': 'bgky',
'bozeman, MT': 'bozeman',
'brainerd, MN': 'brainerd',
'brownsville, TX': 'brownsville',
'brunswick, GA': 'brunswick',
'buffalo, NY': 'buffalo',
'butte, MT': 'butte',
'cape cod / islands': 'capecod',
'catskills': 'catskills',
'cedar rapids, IA': 'cedarrapids',
'central louisiana': 'cenla',
'central michigan': 'centralmich',
'central NJ': 'cnj',
'champaign urbana': 'chambana',
'charleston, SC': 'charleston',
'charleston, WV': 'charlestonwv',
'charlotte, NC': 'charlotte',
'charlottesville, VA': 'charlottesville',
'chattanooga, TN': 'chattanooga',
'chautauqua, NY': 'chautauqua',
'chicago': 'chicago',
'chico, CA': 'chico',
'chillicothe, OH': 'chillicothe',
'cincinnati, OH': 'cincinnati',
'clarksville, TN': 'clarksville',
'cleveland, OH': 'cleveland',
'clovis / portales': 'clovis',
'college station, TX': 'collegestation',
'colorado springs': 'cosprings',
'columbia / jeff city': 'columbiamo',
'columbia, SC': 'columbia',
'columbus, GA': 'columbusga',
'columbus, OH': 'columbus',
'cookeville, TN': 'cookeville',
'corpus christi, TX': 'corpuschristi',
'corvallis/albany': 'corvallis',
'cumberland valley': 'chambersburg',
'dallas / fort worth': 'dallas',
'danville': 'danville',
'daytona beach': 'daytona',
'dayton / springfield': 'dayton',
'decatur, IL': 'decatur',
'deep east texas': 'nacogdoches',
'delaware': 'delaware',
'del rio / eagle pass': 'delrio',
'denver, CO': 'denver',
'des moines, IA': 'desmoines',
'detroit metro': 'detroit',
'dothan, AL': 'dothan',
'dubuque': 'dubuque',
'duluth / superior': 'duluth',
'eastern CO': 'eastco',
'eastern CT': 'newlondon',
'eastern kentucky': 'eastky',
'eastern montana': 'montana',
'eastern NC': 'eastnc',
'eastern panhandle': 'martinsburg',
'eastern shore': 'easternshore',
'east idaho': 'eastidaho',
'east oregon': 'eastoregon',
'eau claire, WI': 'eauclaire',
'elko, NV': 'elko',
'elmira-corning': 'elmira',
'el paso, TX': 'elpaso',
'erie, PA': 'erie',
'eugene, OR': 'eugene',
'evansville, IN': 'evansville',
'fairbanks, AK': 'fairbanks',
'fargo / moorhead': 'fargo',
'farmington, NM': 'farmington',
'fayetteville, AR': 'fayar',
'fayetteville, NC': 'fayetteville',
'finger lakes, NY': 'fingerlakes',
'flagstaff / sedona': 'flagstaff',
'flint, MI': 'flint',
'florence / muscle shoals': 'shoals',
'florence, SC': 'florencesc',
'florida keys': 'keys',
'fort collins / north CO': 'fortcollins',
'fort dodge, IA': 'fortdodge',
'fort smith, AR': 'fortsmith',
'fort wayne, IN': 'fortwayne',
'frederick, MD': 'frederick',
'fredericksburg, VA': 'fredericksburg',
'fresno / madera': 'fresno',
'ft myers / SW florida': 'fortmyers',
'gadsden-anniston': 'gadsden',
'gainesville, FL': 'gainesville',
'galveston, TX': 'galveston',
'glens falls, NY': 'glensfalls',
'gold country': 'goldcountry',
'grand forks': 'grandforks',
'grand island, NE': 'grandisland',
'grand rapids, MI': 'grandrapids',
'great falls, MT': 'greatfalls',
'green bay, WI': 'greenbay',
'greensboro, NC': 'greensboro',
'greenville / upstate': 'greenville',
'gulfport / biloxi': 'gulfport',
'hampton roads': 'norfolk',
'hanford-corcoran': 'hanford',
'harrisburg, PA': 'harrisburg',
'harrisonburg, VA': 'harrisonburg',
'hartford, CT': 'hartford',
'hattiesburg, MS': 'hattiesburg',
'hawaii': 'honolulu',
'heartland florida': 'cfl',
'helena, MT': 'helena',
'hickory / lenoir': 'hickory',
'high rockies': 'rockies',
'hilton head': 'hiltonhead',
'holland, MI': 'holland',
'houma, LA': 'houma',
'houston, TX': 'houston',
'hudson valley, NY': 'hudsonvalley',
'humboldt county': 'humboldt',
'huntington-ashland': 'huntington',
'huntsville / decatur': 'huntsville',
'imperial county': 'imperial',
'indianapolis': 'indianapolis',
'inland empire, CAcounties': 'inlandempire',
'iowa city, IA': 'iowacity',
'ithaca, NY': 'ithaca',
'jackson, MI': 'jxn',
'jackson, MS': 'jackson',
'jackson, TN': 'jacksontn',
'jacksonville, FL': 'jacksonville',
'jacksonville, NC': 'onslow',
'janesville, WI': 'janesville',
'jersey shore': 'jerseyshore',
'jonesboro, AR': 'jonesboro',
'joplin, MO': 'joplin',
'kalamazoo, MI': 'kalamazoo',
'kalispell, MT': 'kalispell',
'kansas city, MO': 'kansascity',
'kenai peninsula': 'kenai',
'kennewick-pasco-richland': 'kpr',
'kenosha-racine': 'racine',
'killeen / temple / ft hood': 'killeen',
'kirksville, MO': 'kirksville',
'klamath falls, OR': 'klamath',
'knoxville, TN': 'knoxville',
'kokomo, IN': 'kokomo',
'la crosse, WI': 'lacrosse',
'lafayette, LA': 'lafayette',
'lafayette / west lafayette': 'tippecanoe',
'lake charles, LA': 'lakecharles',
'lakeland, FL': 'lakeland',
'lake of the ozarks': 'loz',
'lancaster, PA': 'lancaster',
'lansing, MI': 'lansing',
'laredo, TX': 'laredo',
'la salle co': 'lasalle',
'las cruces, NM': 'lascruces',
'las vegas': 'lasvegas',
'lawrence, KS': 'lawrence',
'lawton, OK': 'lawton',
'lehigh valley': 'allentown',
'lewiston / clarkston': 'lewiston',
'lexington, KY': 'lexington',
'lima / findlay': 'limaohio',
'lincoln, NE': 'lincoln',
'little rock': 'littlerock',
'logan, UT': 'logan',
'long island, NY': 'longisland',
'los angeles': 'losangeles',
'louisville, KY': 'louisville',
'lubbock, TX': 'lubbock',
'lynchburg, VA': 'lynchburg',
'macon / warner robins': 'macon',
'madison, WI': 'madison',
'maine': 'maine',
'manhattan, KS': 'ksu',
'mankato, MN': 'mankato',
'mansfield, OH': 'mansfield',
'mason city, IA': 'masoncity',
'mattoon-charleston': 'mattoon',
'mcallen / edinburg': 'mcallen',
'meadville, PA': 'meadville',
'medford-ashland': 'medford',
'memphis, TN': 'memphis',
'mendocino county': 'mendocino',
'merced, CA': 'merced',
'meridian, MS': 'meridian',
'milwaukee, WI': 'milwaukee',
'minneapolis / st paul': 'minneapolis',
'missoula, MT': 'missoula',
'mobile, AL': 'mobile',
'modesto, CA': 'modesto',
'mohave county': 'mohave',
'monroe, LA': 'monroe',
'monroe, MI': 'monroemi',
'monterey bay': 'monterey',
'montgomery, AL': 'montgomery',
'morgantown, WV': 'morgantown',
'moses lake, WA': 'moseslake',
'muncie / anderson': 'muncie',
'muskegon, MI': 'muskegon',
'myrtle beach, SC': 'myrtlebeach',
'nashville, TN': 'nashville',
'new hampshire': 'nh',
'new haven, CT': 'newhaven',
'new orleans': 'neworleans',
'new river valleyradford, etc': 'blacksburg',
'new york city': 'newyork',
'north central FL': 'lakecity',
'north dakota': 'nd',
'northeast SD': 'nesd',
'northern michigan': 'nmi',
'northern panhandle': 'wheeling',
'northern WI': 'northernwi',
'north jersey': 'newjersey',
'north mississippi': 'northmiss',
'north platte, NE': 'northplatte',
'northwest CT': 'nwct',
'northwest GA': 'nwga',
'northwest KS': 'nwks',
'northwest OK': 'enid',
'ocala, FL': 'ocala',
'odessa / midland': 'odessa',
'ogden-clearfield': 'ogden',
'okaloosa / walton': 'okaloosa',
'oklahoma city': 'oklahomacity',
'olympic peninsula': 'olympic',
'omaha / council bluffs': 'omaha',
'oneonta, NY': 'oneonta',
'orange county, CA': 'orangecounty',
'oregon coast': 'oregoncoast',
'orlando, FL': 'orlando',
'outer banks': 'outerbanks',
'owensboro, KY': 'owensboro',
'palm springs, CA': 'palmsprings',
'panama city, FL': 'panamacity',
'parkersburg-marietta': 'parkersburg',
'pensacola, FL': 'pensacola',
'peoria, IL': 'peoria',
'philadelphia': 'philadelphia',
'phoenix, AZ': 'phoenix',
'pierre / central SD': 'csd',
'pittsburgh, PA': 'pittsburgh',
'plattsburgh-adirondacks': 'plattsburgh',
'poconos': 'poconos',
'port huron, MI': 'porthuron',
'portland, OR': 'portland',
'potsdam-canton-massena': 'potsdam',
'prescott, AZ': 'prescott',
'provo / orem': 'provo',
'pueblo, CO': 'pueblo',
'pullman / moscow': 'pullman',
'quad cities, IA/IL': 'quadcities',
'raleigh / durham / CH': 'raleigh',
'rapid city / west SD': 'rapidcity',
'reading, PA': 'reading',
'redding, CA': 'redding',
'reno / tahoe': 'reno',
'rhode island': 'providence',
'richmond, IN': 'richmondin',
'richmond, VA': 'richmond',
'roanoke, VA': 'roanoke',
'rochester, MN': 'rmn',
'rochester, NY': 'rochester',
'rockford, IL': 'rockford',
'roseburg, OR': 'roseburg',
'roswell / carlsbad': 'roswell',
'sacramento': 'sacramento',
'saginaw-midland-baycity': 'saginaw',
'salem, OR': 'salem',
'salina, KS': 'salina',
'salt lake city': 'saltlakecity',
'san angelo, TX': 'sanangelo',
'san antonio': 'sanantonio',
'san diego': 'sandiego',
'sandusky, OH': 'sandusky',
'san luis obispo': 'slo',
'san marcos, TX': 'sanmarcos',
'santa barbara': 'santabarbara',
'santa fe / taos': 'santafe',
'santa maria, CA': 'santamaria',
'sarasota-bradenton': 'sarasota',
'savannah / hinesville': 'savannah',
'scottsbluff / panhandle': 'scottsbluff',
'scranton / wilkes-barre': 'scranton',
'seattle-tacoma': 'seattle',
'SF bay area': 'sfbay',
'sheboygan, WI': 'sheboygan',
'show low, AZ': 'showlow',
'shreveport, LA': 'shreveport',
'sierra vista, AZ': 'sierravista',
'sioux city, IA': 'siouxcity',
'sioux falls / SE SD': 'siouxfalls',
'siskiyou county': 'siskiyou',
'skagit / island / SJI': 'skagit',
'south bend / michiana': 'southbend',
'south coast, MAcounties': 'southcoast',
'south dakota': 'sd',
'southeast alaska': 'juneau',
'southeast IA': 'ottumwa',
'southeast KS': 'seks',
'southeast missouri': 'semo',
'southern illinois': 'carbondale',
'southern maryland': 'smd',
'southern WV': 'swv',
'south floridamiami/dade, broward, and palm beach': 'miami',
'south jersey': 'southjersey',
'southwest KS': 'swks',
'southwest michigan': 'swmi',
'southwest MN': 'marshall',
'southwest MS': 'natchez',
'southwest TX': 'bigbend',
'southwest VA': 'swva',
'space coast, FL': 'spacecoast',
'spokane / coeur d\' alene': 'spokane',
'springfield, IL': 'springfieldil',
'springfield, MO': 'springfield',
'state college, PA': 'pennstate',
'statesboro, GA': 'statesboro',
'st augustine, FL': 'staugustine',
'st cloud, MN': 'stcloud',
'st george, UT': 'stgeorge',
'stillwater, OK': 'stillwater',
'st joseph': 'stjoseph',
'st louis, MO': 'stlouis',
'stockton, CA': 'stockton',
'susanville, CA': 'susanville',
'syracuse, NY': 'syracuse',
'tallahassee': 'tallahassee',
'tampa bay area': 'tampa',
'terre haute, IN': 'terrehaute',
'texarkana': 'texarkana',
'texoma': 'texoma',
'the thumb, MI': 'thumb',
'toledo, OH': 'toledo',
'topeka, KS': 'topeka',
'treasure coast, FL': 'treasure',
'tri-cities, TN': 'tricities',
'tucson, AZ': 'tucson',
'tulsa, OK': 'tulsa',
'tuscaloosa': 'tuscaloosa',
'tuscarawas co': 'tuscarawas',
'twin falls, ID': 'twinfalls',
'twin tiers NY/PA': 'twintiers',
'tyler / east TX': 'easttexas',
'upper peninsula, MI': 'up',
'utica-rome-oneida': 'utica',
'valdosta, GA': 'valdosta',
'ventura county': 'ventura',
'vermont': 'vermont',
'victoria, TX': 'victoriatx',
'visalia-tulare': 'visalia',
'waco, TX': 'waco',
'washington, DC': 'washingtondc',
'waterloo / cedar falls': 'waterloo',
'watertown, NY': 'watertown',
'wausau, WI': 'wausau',
'wenatchee, WA': 'wenatchee',
'western IL': 'quincy',
'western KY': 'westky',
'western maryland': 'westmd',
'western massachusetts': 'westernmass',
'western slope': 'westslope',
'west virginia (old)': 'wv',
'wichita falls, TX': 'wichitafalls',
'wichita, KS': 'wichita',
'williamsport, PA': 'williamsport',
'wilmington, NC': 'wilmington',
'winchester, VA': 'winchester',
'winston-salem, NC': 'winstonsalem',
'worcester / central MA': 'worcester',
'wyoming': 'wyoming',
'yakima, WA': 'yakima',
'york, PA': 'york',
'youngstown, OH': 'youngstown',
'yuba-sutter, CA': 'yubasutter',
'yuma, AZ': 'yuma',
'zanesville / cambridge': 'zanesville'}

loc_dict = OrderedDict(sorted(locations.items(), key=lambda t: t[0]))
